[[redirects]]
  from = "/api/*"
  to = "https://api.r8s.mattschlosser.me/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200